#!/usr/bin/env python
# coding: utf-8
"""运行 QCFP_MTF 测试（无需 pytest）；--unit-only 跳过依赖真实数据库的集成测试"""

import argparse
import importlib
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
CORE_DIR = PROJECT_ROOT / "Core"
if str(CORE_DIR) not in sys.path:
    sys.path.insert(0, str(CORE_DIR))

MODULES = [
    "test_calendar",
    "test_normalization",
    "test_settings",
    "test_evidence",
    "test_loader",
    "test_quality",
    "test_structural.test_chip_factors",
    "test_structural.test_flow_factors",
    "test_structural.test_price_factors",
    "test_structural.test_structural_regime",
    "test_structural.test_divergence",
    "test_structural.test_engine_smoke",
    "test_behavioral.test_turnover_factors",
    "test_behavioral.test_volume_factors",
    "test_behavioral.test_vp_matrix",
    "test_behavioral.test_cbi",
    "test_behavioral.test_cost_position",
    "test_behavioral.test_monthly_stage",
    "test_behavioral.test_engine_smoke",
    "test_tactical.test_weekly_volume",
    "test_tactical.test_weekly_turnover",
    "test_tactical.test_weekly_vwap",
    "test_tactical.test_weekly_signal",
    "test_tactical.test_daily_tactical",
    "test_tactical.test_engine_smoke",
    "test_fusion.test_chip_confidence",
    "test_fusion.test_mtf_alignment",
    "test_fusion.test_mtf_fsm",
    "test_fusion.test_anti_inference",
    "test_fusion.test_tactical_override",
    "test_fusion.test_daily_timing",
    "test_fusion.test_engine_smoke",
    "test_wave.test_wave_lifecycle",
    "test_wave.test_opportunity_v2",
    "test_wave.test_aging",
    "test_wave.test_stage_gate",
    "test_wave.test_quality",
    "test_wave.test_stage_output",
    "test_decision.test_optimal_position",
    "test_market.test_transition_v2",
    "test_market.test_opportunity_regime",
    "test_market.test_regime_fsm",
    "test_market.test_regime_conditioned",
    "test_decision.test_robustness",
    "test_decision.test_ledger_chain",
    "test_decision.test_binding_constraint",
    "test_data.test_lineage",
    "test_data.test_feature_contract",
    "test_portfolio.test_lifecycle_gate",
    "test_portfolio.test_exposure_engine",
    "test_portfolio.test_risk_contagion",
    "test_portfolio.test_drawdown_response",
    "test_portfolio.test_concentration",
    "test_portfolio.test_tail_gap",
    "test_portfolio.test_interaction_graph",
    "test_portfolio.test_strategy_allocation",
    "test_portfolio.test_aggregator",
    "test_portfolio.test_budget",
    "test_ranking.test_opportunity_ranking",
    "test_ranking.test_replacement",
    "test_ranking.test_competition",
    "test_ranking.test_queue",
    "test_monitoring.test_forecast_realized",
    "test_monitoring.test_strategy_health",
    "test_monitoring.test_drift_monitor",
    "test_data.test_quality_gate",
    "test_stress.test_stress_engine",
    "test_ablation.test_statistical",
    "test_ablation.test_research_registry",
    "test_ablation.test_portfolio_counterfactual",
    "test_ablation.test_matrix",
    "test_ablation.test_incremental_alpha",
    "test_alpha.test_registry",
    "test_alpha.test_correlation",
    "test_safety.test_continuous_validation",
    "test_safety.test_safety_case",
    "test_learning.test_controlled_loop",
    "test_learning.test_post_trade",
    "test_learning.test_adaptive_sandbox",
    "test_failure.test_loss_cluster",
    "test_failure.test_taxonomy",
    "test_explainability.test_graph",
    "test_governance.test_version_registry",
    "test_governance.test_version_impact",
    "test_governance.test_research_guard",
    "test_governance.test_promotion_gate",
    "test_governance.test_conflict",
    "test_decision.test_dynamic_risk_budget",
    "test_decision.test_convergence_invariants",
    "test_decision.test_constraint_trace",
    "test_decision.test_reason_codes",
    "test_decision.test_path_hash",
    "test_decision.test_release_identity",
    "test_decision.test_confidence",
    "test_decision.test_permission_policy_object",
    "test_decision.test_ledger_manifest",
    "test_decision.test_consensus",
    "test_decision.test_permission_strength",
    "test_decision.test_exit_efficiency",
    "test_decision.test_position_scaling",
    "test_decision.test_boundary_test",
    "test_evaluation.test_no_trade",
    "test_evaluation.test_miss_analysis",
    "test_evaluation.test_regret",
    "test_evaluation.test_governance_alpha",
    "test_evaluation.test_timing_alpha",
    "test_evaluation.test_position_lifecycle",
    "test_evaluation.test_fpfn_lab",
    "test_evaluation.test_challenger",
    "test_evaluation.test_module_value",
    "test_evaluation.test_regime_matrix",
    "test_explainability.test_engine",
    "test_market.test_regime_robustness",
    "test_review.test_strategic_review",
    "test_failure.test_degradation",
    "test_decision.test_schema_registry",
    "test_decision.test_replay_engine",
    "test_portfolio.test_portfolio_ledger",
    "test_ranking.test_allocator",
    "test_stress.test_scenario_engine",
    "test_stress.test_stress_matrix",
    "test_stress.test_data_degradation",
    "test_stress.test_joint_stress",
    "test_monitoring.test_decision_quality",
    "test_monitoring.test_observability",
    "test_monitoring.test_gap_monitor",
    "test_monitoring.test_confidence_calibration",
    "test_monitoring.test_benchmark",
    "test_monitoring.test_validation_controller",
    "test_governance.test_model_decay",
    "test_governance.test_certification",
    "test_governance.test_alpha_health",
    "test_governance.test_provenance",
    "test_governance.test_autonomy",
    "test_governance.test_evidence_provider",
    "test_governance.test_zero_trust",
    "test_governance.test_artifact_registry",
    "test_governance.test_doubt_index",
    "test_data.test_pit_registry",
    "test_data.test_feature_registry",
    "test_research.test_factory",
    "test_safety.test_system_health",
    "test_safety.test_fail_closed",
    "test_report.test_contract",
    "test_wave.test_canonical_chain",
    "test_wave.test_asof_opportunity",
    "test_ablation.test_paired_ablation",
    "test_decision.test_replay_contract",
    "test_decision.test_types",
    "test_decision.test_decision_delta",
    "test_evaluation.test_decision_stability_diag",
    "test_evaluation.test_trade_outcome",
    "test_evaluation.test_wave_quality_matrix",
    "test_evaluation.test_permission_value",
    "test_evaluation.test_retail_scorecard",
    "test_governance.test_feature_freeze",
    "test_governance.test_release_manifest",
    "test_governance.test_shadow_divergence",
    "test_governance.test_change_impact",
    "test_governance.test_dead_authority",
    "test_config.test_governance",
    "test_data.test_asof_contract",
    "test_data.test_universe_snapshot",
    "test_data.test_tradability",
    "test_monitoring.test_research_production_drift",
    "test_safety.test_incident_protocol",
    "test_performance.test_contract",
    "test_governance.test_validation_certificate",
    "test_governance.test_module_trim",
    "test_decision.test_feature_manifest",
    "test_decision.test_version_identity",
    "test_stress.test_scenario_library",
    "test_decision.test_property_invariants",
    "test_governance.test_three_worlds",
    "test_governance.test_complexity_budget",
    "test_governance.test_module_retirement",
    "test_governance.test_lifecycle_provenance",
    "test_research.test_feature_pruning",
    "test_research.test_overfitting_firewall",
    "test_research.test_ci_engine",
    "test_research.test_simplification",
    "test_research.test_alpha_discovery",
    "test_research.test_causal_evidence",
    "test_research.test_policy_optimizer",
    "test_research.test_strategy_competition",
    "test_research.test_transferability",
    "test_research.test_autonomous_loop",
    "test_alpha.test_halflife",
    "test_evaluation.test_counterfactual_value",
    "test_scripts.test_canonical_only",
    "test_governance.test_trade_frequency",
    "test_portfolio.test_rebalancing",
    "test_backtest.test_retail_utility",
    "test_decision.test_action_generator",
    "test_decision.test_risk_evaluator",
    "test_decision.test_dss_output",
    "test_decision.test_dss_pit",
    "test_decision.test_catalyst_quality",
    "test_decision.test_retail",
    "test_decision.test_institutional_filter",
    "test_decision.test_institutional_permission",
    "test_decision.test_retail_position_fsm",
    "test_decision.test_2dot2_engines",
    "test_decision.test_decision_invariants",
    "test_decision.test_governance",
    "test_decision.test_governance_matrix",
    "test_decision.test_governance_contract",
    "test_decision.test_tactical_chain",
    "test_decision.test_00371_downtrend_exit",
    "test_decision.test_unified_object",
    "test_decision.test_entry_exit_quality",
    "test_decision.test_time_in_trade",
    "test_decision.test_progressive_sizing",
    "test_decision.test_replay_cert",
    "test_decision.test_engine_smoke",
    "test_e2e.test_e2e_consistency",
    "test_golden.test_golden_cases",
    "test_backtest.test_lookahead_filter",
    "test_backtest.test_data_pipeline",
    "test_backtest.test_engine",
    "test_backtest.test_performance",
    "test_backtest.test_calibration",
    "test_backtest.test_asof",
    "test_backtest.test_invariants",
    "test_backtest.test_financial_invariants",
    "test_backtest.test_wave_capture",
    "test_backtest.test_canonical",
    "test_backtest.test_research_gate",
    "test_backtest.test_execution_simulator",
    "test_backtest.test_cost_breakeven",
    "test_backtest.test_oos_summary",
    "test_backtest.test_parameter_stability",
    "test_backtest.test_canonical_provenance",
    "test_execution.test_liquidity_exit",
    "test_execution.test_execution_pipeline",
    "test_execution.test_strategy_capacity",
    "test_performance.test_attribution",
    "test_backtest.test_engine_smoke",
    # 收尾/证明/减法（新 41–50）
    "test_decision.test_schema_contract",
    "test_golden.test_golden_constitution",
    "test_governance.test_determinism",
    "test_decision.test_field_lineage",
    "test_monitoring.test_execution_calibration",
    "test_governance.test_decision_changelog",
    "test_decision.test_abstain",
    "test_governance.test_failure_injection",
    "test_governance.test_architecture_conformance",
    "test_governance.test_simplification_release",
    # 生产证据/基准对照/研究可重复/决策成本/可观测性/最终瘦身（新 51–60）
    "test_governance.test_production_acceptance",
    "test_research.test_benchmark_ladder",
    "test_evaluation.test_decision_cost_budget",
    "test_evaluation.test_counterfactual_audit",
    "test_research.test_research_artifact_bundle",
    "test_research.test_negative_result_registry",
    "test_monitoring.test_critical_path_observability",
    "test_monitoring.test_decision_coverage",
    "test_research.test_minimum_viable_canonical",
    "test_governance.test_complexity_ceiling",
    # 长期治理/边界管理/防止系统重新复杂化（新 61–70）
    "test_governance.test_human_override",
    "test_evaluation.test_override_outcome_review",
    "test_research.test_threshold_sensitivity_map",
    "test_research.test_rule_interaction_audit",
    "test_monitoring.test_binding_constraint_frequency",
    "test_monitoring.test_risk_budget_utilization",
    "test_evaluation.test_opportunity_funnel",
    "test_monitoring.test_decision_latency_budget",
    "test_report.test_information_budget",
    "test_governance.test_completeness_review",
    # 证据闭环/长期可维护/规则退役/防回复杂（新 71–80）
    "test_governance.test_decision_necessity",
    "test_governance.test_rule_ownership",
    "test_governance.test_duplicate_logic_detector",
    "test_evaluation.test_decision_surface_audit",
    "test_evaluation.test_risk_reduction_attribution",
    "test_failure.test_decision_error_taxonomy",
    "test_safety.test_recovery_replay_test",
    "test_governance.test_research_debt_register",
    "test_governance.test_production_simplicity_kpi",
    "test_governance.test_system_constitution",
    # 防回归/长期证据维护/治理老化/最终删减（新 81–90）
    "test_governance.test_governance_aging",
    "test_governance.test_evidence_expiry",
    "test_governance.test_rule_removal_test",
    "test_research.test_dominated_rule_detection",
    "test_evaluation.test_decision_compression",
    "test_monitoring.test_state_transition_audit",
    "test_governance.test_cross_layer_contradiction",
    "test_governance.test_research_production_leakage",
    "test_decision.test_historical_integrity",
    "test_governance.test_minimal_governed_core",
    # 终局治理/证据压缩/长期退役/系统退出机制（新 91–100）
    "test_governance.test_production_evidence_pack",
    "test_governance.test_certification_scope",
    "test_research.test_evidence_hierarchy",
    "test_research.test_evidence_contradiction",
    "test_governance.test_sunset_policy",
    "test_safety.test_strategy_kill",
    "test_safety.test_reactivation_gate",
    "test_governance.test_governance_minimalism",
    "test_governance.test_one_page_canonical",
    "test_governance.test_final_design_principles",
    # 新一轮 1–10：收权 / 硬约束 / 事实链 / Wave 核心 / 统一验证
    "test_backtest.test_evidence_authority",
    "test_decision.test_governance_caps",
    "test_decision.test_permission_derisk",
    "test_decision.test_ledger_append_only",
    "test_decision.test_wave_canonical_wiring",
    "test_decision.test_certified_decision",
    "test_report.test_report_ledger_only",
    "test_backtest.test_canonical_runs",
    "test_ablation.test_paired_ablation_fix",
    "test_governance.test_convergence_release",
    # 新一轮 11–20：统一认证/报告证明/版本唯一/治理接线/物理删除
    "test_governance.test_validation_certificate_authority",
    "test_decision.test_governance_card",
    "test_governance.test_version_identity_single_source",
    "test_decision.test_evidence_pack_bound",
    "test_governance.test_change_impact_gate",
    "test_monitoring.test_critical_path_from_snapshot",
    "test_governance.test_production_feature_manifest",
    "test_governance.test_physical_retirement_gate",
    "test_evaluation.test_funnel_from_snapshots",
    "test_governance.test_architecture_gate",
    # 新一轮 21–30：PIT 时间完整/实盘可执行/决策解释/牛散评估/压缩复杂度
    "test_data.test_asof_time_completeness",
    "test_data.test_universe_snapshot_v2",
    "test_data.test_tradability_hard_gate",
    "test_decision.test_decision_delta_v2",
    "test_monitoring.test_binding_constraint_attribution",
    "test_monitoring.test_execution_calibration_downgrade",
    "test_monitoring.test_decision_coverage_v2",
    "test_research.test_benchmark_ladder_v2",
    "test_evaluation.test_retail_promotion",
    "test_governance.test_minimum_governed_core_decision",
    # 新一轮 31–40：发布治理/运行期安全/漂移/故障恢复/物理退役
    "test_governance.test_release_identity",
    "test_config.test_decision_critical_config",
    "test_data.test_trading_session_contract",
    "test_data.test_universe_investability",
    "test_data.test_tradability_authority",
    "test_governance.test_shadow_divergence_reason",
    "test_monitoring.test_drift_lifecycle",
    "test_governance.test_change_blast_radius",
    "test_safety.test_incident_policy_table",
    "test_governance.test_dead_authority_dependency",
    # 新一轮 41–50：确定性/Replay 精度/Schema 稳定/历史完整性/故障攻击/复杂度封顶
    "test_decision.test_schema_migration",
    "test_governance.test_golden_corpus",
    "test_governance.test_determinism_identity",
    "test_decision.test_field_lineage_from_snapshot",
    "test_decision.test_path_hash_v2",
    "test_decision.test_historical_integrity_immutable",
    "test_decision.test_abstain_semantics",
    "test_governance.test_failure_injection_suite",
    "test_governance.test_dependency_allowlist",
    "test_governance.test_complexity_ceiling_v2",
    # 新一轮 51–60：已有模块升级为不可绕过的 Production/Research Gate
    "test_governance.test_production_acceptance_gate",
    "test_research.test_promotion_ladder",
    "test_evaluation.test_retail_practicality_gate",
    "test_evaluation.test_counterfactual_from_snapshot",
    "test_research.test_promotion_artifact",
    "test_research.test_feature_proposal_gate",
    "test_monitoring.test_decision_layer_outcome",
    "test_monitoring.test_report_completeness",
    "test_research.test_minimum_canonical_recommendation",
    "test_governance.test_complexity_veto",
    # 新一轮 61–70：人工责任闭环/规则删重/资金效率/为什么没交易/报告压缩/关门
    "test_governance.test_override_ledger_chain",
    "test_evaluation.test_override_quarterly",
    "test_research.test_critical_threshold_review",
    "test_research.test_rule_action_candidates",
    "test_monitoring.test_retirement_evidence",
    "test_monitoring.test_risk_efficiency_report",
    "test_evaluation.test_funnel_from_ledger",
    "test_monitoring.test_latency_value_justification",
    "test_report.test_main_report_sections",
    "test_governance.test_governance_closeout",
    # 新一轮 71–80：必要性证明/唯一归属/主动删重/错误归因/恢复/研究债务/简洁度/宪法
    "test_governance.test_necessity_verdict",
    "test_governance.test_rule_owner_violation",
    "test_governance.test_duplicate_authority_gate",
    "test_evaluation.test_cliff_classification",
    "test_evaluation.test_risk_module_verdict",
    "test_failure.test_trade_postmortem",
    "test_safety.test_recovery_state_consistency",
    "test_governance.test_experimental_aging",
    "test_governance.test_release_simplicity_verdict",
    "test_governance.test_constitution_gate",
    # 新一轮 81–90：规则老化/证据过期/主动删除/状态压缩/研究隔离/历史保护/最小核心
    "test_governance.test_aging_promotion_gate",
    "test_governance.test_expired_certificate_block",
    "test_governance.test_rule_removal_candidates",
    "test_research.test_dominated_to_removal",
    "test_evaluation.test_compression_adoption",
    "test_monitoring.test_state_value_audit",
    "test_governance.test_authority_boundary_violation",
    "test_governance.test_leakage_zero_tolerance",
    "test_decision.test_release_historical_replay",
    "test_governance.test_production_chain_completeness",
    # 新一轮 91–100：证据封装/认证边界/退出重启/治理瘦身/架构定稿/停止规则
    "test_governance.test_evidence_pack_ledger_binding",
    "test_governance.test_claim_within_certified",
    "test_research.test_evidence_lifecycle",
    "test_research.test_contradiction_report",
    "test_governance.test_retirement_condition",
    "test_safety.test_strategy_not_stock",
    "test_safety.test_reactivation_certificate",
    "test_governance.test_governance_component_verdict",
    "test_governance.test_architecture_contract",
    "test_governance.test_final_design_gate",
    # Convergence Release 1–10：唯一决策链/事实链/认证链
    "test_decision.test_certify_fail_closed",
    "test_decision.test_proposal_action",
    "test_decision.test_wave_proposal_monotonic",
    "test_decision.test_canonical_action_invariant",
    "test_decision.test_caps_unknown_degrades",
    "test_decision.test_ledger_dual_chain",
    "test_research.test_formal_research_evidence_only",
    "test_governance.test_validation_sole_authority",
    "test_ablation.test_formal_ablation_authority",
    "test_wave.test_wave_taxonomy_split",
    "test_governance.test_convergence_gate",
    # Release 2（11–20）：Production Identity + Execution Reality + Deterministic Trust
    "test_decision.test_permission_semantics_unified",
    "test_decision.test_release_identity_chain",
    "test_decision.test_path_hash_release2",
    "test_governance.test_golden_release_gate",
    "test_execution.test_executable_target",
    "test_execution.test_order_state_machine",
    "test_monitoring.test_runtime_critical_path",
    "test_governance.test_performance_metric_contract",
    "test_governance.test_participating_manifest",
    "test_governance.test_failure_qualification",
    # Release 3（21–30）：Evidence of Necessity & Controlled Evolution
    "test_decision.test_schema_release_hard_gate",
    "test_decision.test_historical_corpus",
    "test_governance.test_version_impact_gate",
    "test_monitoring.test_oos_coverage_requirement",
    "test_monitoring.test_constraint_keep_verdict",
    "test_monitoring.test_risk_budget_lineage",
    "test_evaluation.test_practicality_hard_gate",
    "test_research.test_oos_benchmark_table",
    "test_research.test_major_release_minimal_answer",
    "test_governance.test_complexity_veto_release",
    "test_monitoring.test_data_trust_report",
    # PWC-1 Production Wiring Closure（1–10）
    "test_decision.test_path_hash_action_change",
    "test_data.test_quality_gate_fail_closed",
    "test_governance.test_cross_binding_certification",
    "test_decision.test_ledger_commit_invariants",
    "test_decision.test_unknown_caps_no_exit",
    "test_backtest.test_formal_stress_canonical_only",
    "test_governance.test_pwc1_retirement",
    "test_governance.test_pwc2_authority_graph",
    "test_governance.test_minimal_trusted_release",
    "test_scripts.test_mtr_closure_scan",
    "test_scripts.test_mtr_pure_referee",
    # Runtime Evidence Closure（Sprint 1–4）
    "test_execution.test_execution_context",
    "test_execution.test_deployment_cap",
    "test_execution.test_broker_adapter",
    "test_execution.test_runtime_event_ledger",
    "test_research.test_research_outcome",
    "test_research.test_outcome_production_boundary",
    "test_execution.test_paper_pipeline",
    "test_execution.test_runtime_schema_and_bypass",
    "test_scripts.test_shadow_universe",
    "test_scripts.test_runtime_evidence_runner",
    "test_monitoring.test_runtime_evidence",
    # 流程治理工程（Flow Governance Engineering）：Sprint A-D
    "test_governance.test_flow_governance",
    # FGC-1 Governance Bypass Test（恶意绕流程验收）
    "test_governance.test_governance_bypass",
    # Phase 1 — Architecture & Specification Freeze
    "test_governance.test_phase1",
    # Phase 4 — Flow Governance Closure（FGC-1 + SF-1~SF-5）
    "test_governance.test_phase4",
]

# 依赖真实数据库/项目配置的集成测试模块（--unit-only 时跳过）
INTEGRATION_MODULES = {
    "test_loader",
    "test_structural.test_engine_smoke",
    "test_behavioral.test_engine_smoke",
    "test_tactical.test_engine_smoke",
    "test_fusion.test_engine_smoke",
    "test_decision.test_engine_smoke",
    "test_decision.test_dss_pit",
    "test_backtest.test_engine_smoke",
}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="QCFP-MTF 测试运行器")
    parser.add_argument("--unit-only", action="store_true",
                        help="只运行纯单元测试（跳过依赖真实数据库的集成测试）")
    args = parser.parse_args(argv)
    modules = [m for m in MODULES
               if not (args.unit_only and m in INTEGRATION_MODULES)]
    failed = []
    for mod_name in modules:
        mod = importlib.import_module(f"QCFP_MTF.tests.{mod_name}")
        tests = [(n, fn) for n, fn in sorted(vars(mod).items())
                 if n.startswith("test_") and callable(fn)]
        print(f"\n=== {mod_name}（{len(tests)} 项）===")
        for name, fn in tests:
            try:
                fn()
                print(f"  PASS {name}")
            except Exception as e:
                failed.append(f"{mod_name}.{name}: {e}")
                print(f"  FAIL {name}: {e}")
    print("\n" + "=" * 50)
    if failed:
        print(f"❌ {len(failed)} 项失败:")
        for f in failed:
            print(f"  - {f}")
        return 1
    label = "纯单元测试" if args.unit_only else "全部测试"
    print(f"✅ {label}通过（{len(modules)} 个模块）")
    return 0


if __name__ == "__main__":
    sys.exit(main())
