# coding: utf-8
"""QCFP-MTF 版本身份（Governance Hardening）

一个具体决策必须能回答"是哪个系统产生的"：
    MODEL_VERSION    系统发布版本（QCFP-MTF-2.5.0）
    RULE_VERSION     决策规则版本（GOV-2.5.0）
    SCHEMA_VERSION   决策快照/台账 Schema（DECISION-1.1）
    FEATURE_SET      功能清单（每项独立版本），feature_manifest_hash 固化

配合 settings_hash / input_fingerprint / run_id 构成完整 Decision Identity。
"""

import hashlib
import json

MODEL_VERSION = "QCFP-MTF-2.5.0"
DECISION_RULE_VERSION = "GOV-2.5.0"
SCHEMA_VERSION = "DECISION-1.1"

# MTR Closure Release（Sprint A–E）：唯一发布标签，进入 Release 身份链。
RELEASE_TAG = "MTR-CLOSURE-1"


class VersionIdentity:
    """唯一版本身份（16 号）：所有 Report/Snapshot/Ledger/Backtest/
    ValidationCertificate 都从这里读取，禁止手工硬编码生产版本号。
    """

    def __init__(self, model_version=MODEL_VERSION,
                 decision_schema_version=SCHEMA_VERSION,
                 governance_rule_version=DECISION_RULE_VERSION,
                 engine_version="canonical-2.8",
                 commit_hash="", config_hash="",
                 feature_hash=None):
        self.model_version = model_version
        self.decision_schema_version = decision_schema_version
        self.governance_rule_version = governance_rule_version
        self.engine_version = engine_version
        self.commit_hash = commit_hash
        self.config_hash = config_hash
        self.feature_manifest_hash = feature_hash \
            or feature_manifest_hash()

    def as_dict(self) -> dict:
        return {
            "model_version": self.model_version,
            "decision_schema_version": self.decision_schema_version,
            "governance_rule_version": self.governance_rule_version,
            "engine_version": self.engine_version,
            "commit_hash": self.commit_hash,
            "config_hash": self.config_hash,
            "feature_manifest_hash": self.feature_manifest_hash,
        }


FEATURE_SET = {
    "institutional_permission": "v1",
    "participation_budget": "v1",
    "retail_fsm": "v31",
    "hard_exit": "v24",
    "downside_risk": "v18",
    "trend_survival": "v1",
    "trade_quality": "v1",
    # 2.8（11–20 优先修改项）
    "unified_decision_object": "v2",
    "wave_lifecycle": "v1",
    "wave_opportunity_v2": "v1",
    "entry_quality": "v2",
    "exit_quality": "v2",
    "time_in_trade": "v1",
    "progressive_sizing": "v1",
    "liquidity_exit": "v2",
    "counterfactual_replay": "v1",
    "replay_cert": "v2",
    # 2.8（21–30 优先修改项）
    "portfolio_lifecycle_gate": "v1",
    "opportunity_ranking_v2": "v1",
    "replacement_stage_aware": "v1",
    "stratified_calibration": "v1",
    "controlled_learning_loop": "v1",
    "stress_liquidity_shocks": "v1",
    "execution_pipeline": "v1",
    "pnl_attribution": "v1",
    "statistical_validation": "v1",
    "continuous_validation": "v1",
    # 2.8（31–40 优先修改项）
    "data_lineage": "v1",
    "feature_contract": "v1",
    "exposure_engine": "v1",
    "risk_contagion": "v1",
    "strategy_capacity": "v1",
    "version_registry_v2": "v1",
    "version_impact": "v1",
    "explainability_graph_v2": "v1",
    "research_registry": "v1",
    "production_gate_v2": "v1",
    # 2.8（41–50 优先修改项）
    "regime_transition_v2": "v1",
    "opportunity_aging": "v1",
    "dynamic_risk_budget": "v1",
    "drawdown_response": "v1",
    "loss_cluster": "v1",
    "opportunity_competition": "v1",
    "portfolio_counterfactual": "v1",
    "failure_taxonomy": "v1",
    "strategy_health": "v1",
    "research_guard": "v1",
    # 收敛工程（新 1–10 系统宪法）
    "permission_gate": "v1",
    "governance_proof_v2": "v1",
    "target_chain_v2": "v1",
    "ledger_fsm_authority": "v1",
    "information_set": "v1",
    "feature_contract_gate": "v1",
    "wave_stage_gate": "v1",
    "convergence_invariants": "v1",
    # 第三层（新 21–30：组合/成交/研究/数据/监控）
    "portfolio_budget": "v1",
    "effective_risk_exposure": "v1",
    "capacity_cap_target": "v1",
    "execution_gap_model": "v1",
    "cost_breakeven": "v1",
    "oos_summary": "v1",
    "parameter_stability": "v1",
    "ablation_matrix": "v1",
    "data_quality_gate": "v1",
    "drift_monitor": "v1",
    # 第四层（新 31–40：解释/可复现/异常/版本治理）
    "explanation_engine": "v1",
    "constraint_trace": "v1",
    "reason_codes": "v1",
    "decision_path_hash": "v1",
    "release_identity": "v1",
    "research_registry_v2": "v1",
    "holdout_lock": "v1",
    "regime_robustness": "v1",
    "failure_degradation": "v1",
    "promotion_gate": "v1",
    # 第五层（新 41–50：工程化/规模化/长期稳定/生产闭环）
    "schema_registry": "v1",
    "full_data_lineage": "v1",
    "deterministic_replay": "v1",
    "portfolio_ledger": "v1",
    "cross_symbol_allocator": "v1",
    "scenario_engine": "v1",
    "decision_quality_monitor": "v1",
    "model_decay": "v1",
    "operational_observability": "v1",
    "governance_certification": "v1",
    # 第六层（新 51–60：资本智能/冲突/实盘偏差/闭环归因）
    "risk_adjusted_opportunity": "v1",
    "capital_allocator_v2": "v1",
    "opportunity_queue": "v1",
    "conflict_resolver_v2": "v1",
    "confidence_position": "v1",
    "module_consensus": "v1",
    "gap_monitor": "v1",
    "post_trade_attribution": "v1",
    # 第七层（新 61–70：决策校准/组合优化/行为控制/Alpha归因/自适应治理）
    "confidence_calibration": "v1",
    "opportunity_decay": "v1",
    "mfe_mae_benchmark": "v1",
    "holding_efficiency": "v1",
    "capital_rotation": "v1",
    "rebalancing_governance": "v1",
    "trade_frequency_governor": "v1",
    "alpha_attribution_v2": "v1",
    "adaptive_sandbox": "v1",
    "validation_controller": "v1",
    # 第八层（新 71–80：市场机会环境/时机/组合生存）
    "opportunity_regime": "v1",
    "permission_strength": "v1",
    "wave_quality_decomposition": "v1",
    "exit_efficiency": "v1",
    "position_scaling": "v1",
    "concentration_governor": "v1",
    "tail_gap_risk": "v1",
    "alpha_capacity": "v1",
    "strategic_review": "v1",
    # 第九层（新 81–90：Alpha 资产治理/因果/状态切换/组合交互/溯源）
    "alpha_registry": "v1",
    "alpha_correlation": "v1",
    "incremental_alpha": "v1",
    "causal_attribution": "v1",
    "regime_fsm": "v1",
    "interaction_graph": "v1",
    "strategy_allocation": "v1",
    "alpha_health": "v1",
    "research_provenance": "v1",
    # 第十层（新 91–100：系统自证/压力生存/决策鲁棒性/联合退化/自治）
    "decision_robustness": "v1",
    "stress_matrix": "v1",
    "data_degradation": "v1",
    "joint_stress": "v1",
    "boundary_test": "v1",
    "no_trade_quality": "v1",
    "miss_analysis": "v1",
    "regret_analysis": "v1",
    "safety_case": "v1",
    "autonomy_governor": "v1",
    # Evidence-First 可信底座（新 1–10）
    "canonical_only": "v1",
    "ledger_hash_chain": "v1",
    "evidence_provider": "v1",
    "zero_trust_cert": "v1",
    "pit_universe_registry": "v1",
    "artifact_registry": "v1",
    "binding_constraint": "v1",
    "governance_alpha": "v1",
    "timing_alpha": "v1",
    "model_doubt_index": "v1",
    # 实战能力/研究效率/系统质量（新 11–20）
    "data_health_score": "v1",
    "feature_registry": "v1",
    "regime_conditioned": "v1",
    "wave_stage_output": "v1",
    "position_lifecycle": "v1",
    "portfolio_aggregator": "v1",
    "executable_target": "v1",
    "joint_scenario_engine": "v1",
    "research_factory": "v1",
    "system_health": "v1",
    # Intelligence Layer（新 21–30）
    "provenance_graph": "v1",
    "conflict_regime": "v1",
    "calibration_logloss_ece": "v1",
    "optimal_position": "v1",
    "fpfn_lab": "v1",
    "challenger_system": "v1",
    "three_worlds": "v1",
    # 克制层（新 31–40：复杂度控制/反过拟合/统计可信/退役机制）
    "module_value_attribution": "v1",
    "complexity_budget_v2": "v1",
    "feature_pruning": "v1",
    "overfitting_firewall": "v1",
    "ci_engine": "v1",
    "regime_strategy_matrix": "v1",
    "simplification_engine": "v1",
    "module_retirement": "v1",
    # Adaptive Intelligence（新 41–50）
    "alpha_discovery": "v1",
    "counterfactual_value": "v1",
    "causal_evidence": "v1",
    "policy_optimizer": "v1",
    "alpha_halflife": "v1",
    "strategy_competition": "v1",
    "transferability": "v1",
    "autonomous_research_loop": "v1",
    # 权力边界收敛/生产治理闭环/Wave 强化（新 1–10）
    "canonical_provenance": "v1",
    "permission_policy_unified": "v1",
    "dataset_manifest": "v1",
    "fail_closed_validation": "v1",
    "lifecycle_provenance": "v1",
    "report_contract": "v1",
    "wave_canonical_chain": "v1",
    "asof_wave_opportunity": "v1",
    "paired_ablation": "v1",
    # 统一口径/证明约束/删除冗余（新 11–20）
    "performance_contract": "v1",
    "trading_day_deleverage": "v1",
    "validation_certificate": "v1",
    "feature_manifest": "v1",
    "version_identity": "v1",
    "standard_reason_codes": "v1",
    "scenario_library": "v1",
    "module_trim": "v1",
    # 实战校准/边界验证/研究治理/运维可控（新 21–30）
    "replay_contract": "v1",
    "evidence_quality_contract": "v1",
    "decision_types": "v1",
    "decision_delta": "v1",
    "stability_diagnostics": "v1",
    "trade_outcome_attribution": "v1",
    "wave_quality_matrix": "v1",
    "permission_value": "v1",
    "retail_scorecard": "v1",
    "feature_freeze": "v1",
    # P3 工程确定性/生产一致性/Shadow 监督/变更控制/真正退役（新 31–40）
    "release_manifest": "v1",
    "config_governance": "v1",
    "asof_time_contract": "v1",
    "universe_snapshot_contract": "v1",
    "tradability_governance": "v1",
    "shadow_divergence_monitor": "v1",
    "research_production_drift": "v1",
    "change_impact_matrix": "v1",
    "incident_protocol": "v1",
    "dead_authority_removal": "v1",
    # 收尾/证明/减法（新 41–50：Schema 契约/黄金宪法/确定性/血缘/
    # 执行校准/变更日志/弃权/注入测试/架构一致性/简化发布）
    "schema_contract": "v1",
    "golden_constitution": "v1",
    "determinism_contract": "v1",
    "field_lineage": "v1",
    "execution_calibration": "v1",
    "decision_changelog": "v1",
    "abstain_no_decision": "v1",
    "failure_injection": "v1",
    "architecture_conformance": "v1",
    "simplification_release": "v1",
    # 生产证据/基准对照/研究可重复/决策成本/可观测性/最终瘦身（新 51–60）
    "production_acceptance_contract": "v1",
    "benchmark_ladder": "v1",
    "decision_cost_budget": "v1",
    "counterfactual_audit": "v1",
    "research_artifact_bundle": "v1",
    "negative_result_registry": "v1",
    "critical_path_observability": "v1",
    "decision_coverage": "v1",
    "minimum_viable_canonical": "v1",
    "complexity_ceiling": "v1",
    # 长期治理/边界管理/防止系统重新复杂化（新 61–70）
    "human_override_contract": "v1",
    "override_outcome_review": "v1",
    "threshold_sensitivity_map": "v1",
    "rule_interaction_audit": "v1",
    "binding_constraint_frequency": "v1",
    "risk_budget_utilization": "v1",
    "opportunity_funnel": "v1",
    "decision_latency_budget": "v1",
    "report_information_budget": "v1",
    "governance_completeness_review": "v1",
    # 证据闭环/长期可维护/规则退役/防回复杂（新 71–80）
    "decision_necessity_audit": "v1",
    "rule_ownership_registry": "v1",
    "duplicate_logic_detector": "v1",
    "decision_surface_audit": "v1",
    "risk_reduction_attribution": "v1",
    "decision_error_taxonomy": "v1",
    "recovery_replay_test": "v1",
    "research_debt_register": "v1",
    "production_simplicity_kpi": "v1",
    "system_constitution": "v1",
    # 防回归/长期证据维护/治理老化/最终删减（新 81–90）
    "governance_aging_review": "v1",
    "evidence_expiry_policy": "v1",
    "rule_removal_test": "v1",
    "dominated_rule_detection": "v1",
    "decision_compression_test": "v1",
    "state_transition_audit": "v1",
    "cross_layer_contradiction": "v1",
    "research_production_leakage": "v1",
    "historical_decision_integrity": "v1",
    "minimal_governed_core": "v1",
    # 终局治理/证据压缩/长期退役/系统退出机制（新 91–100）
    "production_evidence_pack": "v1",
    "certification_scope": "v1",
    "evidence_hierarchy": "v1",
    "evidence_contradiction": "v1",
    "sunset_policy": "v1",
    "strategy_kill_criteria": "v1",
    "reactivation_gate": "v1",
    "governance_minimalism": "v1",
    "one_page_canonical": "v1",
    "final_design_principles": "v1",
    # 新一轮 1–10：收权 / 硬约束 / 事实链 / Wave 核心 / 统一验证
    "evidence_no_decision_authority": "v1",
    "governance_caps": "v1",
    "permission_policy_derisk": "v1",
    "ledger_append_only_dual_chain": "v1",
    "wave_canonical_wiring": "v1",
    "certified_decision_gate": "v1",
    "report_snapshot_ledger_only": "v1",
    "canonical_only_research_runs": "v1",
    "paired_ablation_signflip": "v1",
    "convergence_simplification_release": "v1",
    # 新一轮 11–20：统一认证/报告证明/版本唯一/治理接线/物理删除
    "validation_certificate_authority": "v1",
    "governance_card_real_proofs": "v1",
    "version_identity_single_source": "v1",
    "evidence_pack_bound_to_decision": "v1",
    "change_impact_release_gate": "v1",
    "critical_path_from_snapshot": "v1",
    "production_feature_manifest": "v1",
    "physical_retirement_gate": "v1",
    "opportunity_funnel_from_snapshots": "v1",
    "architecture_conformance_gate": "v1",
    # 新一轮 21–30：PIT 时间完整/实盘可执行/决策解释/牛散评估/压缩复杂度
    "asof_time_completeness": "v1",
    "universe_snapshot_tradable": "v1",
    "tradability_hard_gate": "v1",
    "decision_delta_v2": "v1",
    "binding_constraint_attribution": "v1",
    "execution_calibration_downgrade": "v1",
    "decision_coverage_v2": "v1",
    "benchmark_ladder_baselines": "v1",
    "retail_practicality_promotion": "v1",
    "minimum_governed_core_decision": "v1",
    # 新一轮 31–40：发布治理/运行期安全/漂移/故障恢复/物理退役
    "production_release_identity": "v1",
    "decision_critical_config_gate": "v1",
    "market_session_time_contract": "v1",
    "universe_investability_state": "v1",
    "tradability_single_authority": "v1",
    "shadow_divergence_reason": "v1",
    "drift_lifecycle_transition": "v1",
    "change_blast_radius": "v1",
    "incident_policy_table": "v1",
    "dead_authority_dependency_check": "v1",
    # 新一轮 41–50：确定性/Replay 精度/Schema 稳定/历史完整性/故障攻击/复杂度封顶
    "schema_migration_gate": "v1",
    "golden_decision_corpus": "v1",
    "determinism_replay_identity": "v1",
    "field_lineage_from_snapshot": "v1",
    "path_hash_binding_caps": "v1",
    "historical_fact_immutable": "v1",
    "abstain_canonical_semantics": "v1",
    "failure_injection_suite": "v1",
    "production_dependency_allowlist": "v1",
    "complexity_ceiling_v2": "v1",
    # 新一轮 51–60：已有模块升级为不可绕过的 Production/Research Gate
    "production_acceptance_total_gate": "v1",
    "promotion_requires_ladder": "v1",
    "retail_practicality_gate": "v1",
    "counterfactual_from_snapshot": "v1",
    "promotion_requires_artifact": "v1",
    "feature_proposal_gate": "v1",
    "decision_layer_outcome": "v1",
    "report_completeness_check": "v1",
    "minimum_canonical_recommendation": "v1",
    "complexity_promotion_veto": "v1",
    # 新一轮 61–70：人工责任闭环/规则删重/资金效率/为什么没交易/报告压缩/关门
    "override_ledger_chain": "v1",
    "override_quarterly_review": "v1",
    "critical_threshold_review": "v1",
    "rule_action_candidates": "v1",
    "retirement_evidence": "v1",
    "risk_efficiency_report": "v1",
    "funnel_from_ledger": "v1",
    "latency_value_justification": "v1",
    "main_report_sections": "v1",
    "governance_closeout": "v1",
    # 新一轮 71–80：必要性证明/唯一归属/主动删重/错误归因/恢复/研究债务/简洁度/宪法
    "necessity_periodic_review": "v1",
    "canonical_rule_owners": "v1",
    "duplicate_authority_release_gate": "v1",
    "cliff_classification": "v1",
    "risk_module_verdict": "v1",
    "trade_postmortem": "v1",
    "recovery_state_consistency": "v1",
    "experimental_feature_aging": "v1",
    "release_simplicity_verdict": "v1",
    "constitution_gate_12": "v1",
    # 新一轮 81–90：规则老化/证据过期/主动删除/状态压缩/研究隔离/历史保护/最小核心
    "aging_promotion_gate": "v1",
    "expired_certificate_block": "v1",
    "rule_removal_candidates": "v1",
    "dominated_to_removal": "v1",
    "compression_adoption": "v1",
    "state_value_audit": "v1",
    "authority_boundary_violation": "v1",
    "leakage_zero_tolerance": "v1",
    "release_historical_replay_check": "v1",
    "production_chain_completeness": "v1",
    # 新一轮 91–100：证据封装/认证边界/退出重启/治理瘦身/架构定稿/停止规则
    "evidence_pack_ledger_binding": "v1",
    "claim_within_certified": "v1",
    "evidence_level_lifecycle": "v1",
    "contradiction_promotion_report": "v1",
    "retirement_condition_required": "v1",
    "strategy_not_stock_answer": "v1",
    "reactivation_requires_certificate": "v1",
    "governance_component_verdict": "v1",
    "architecture_contract_check": "v1",
    "final_design_principle_gate": "v1",
    # Convergence Release 1–10：唯一决策链/事实链/认证链
    "certify_fail_closed": "v1",
    "proposal_action_classifier": "v1",
    "wave_proposal_monotonic": "v1",
    "canonical_action_invariant": "v1",
    "caps_unknown_degrade": "v1",
    "ledger_global_run_split": "v1",
    "formal_research_evidence_only": "v1",
    "validation_sole_authority": "v1",
    "formal_ablation_authority": "v1",
    "wave_taxonomy_single": "v1",
    "convergence_release_gate": "v1",
    # Release 2（11–20）：Production Identity + Execution Reality + Deterministic Trust
    "permission_semantics_unified": "v1",
    "release_identity_chain": "v1",
    "path_hash_release2": "v1",
    "golden_release_gate": "v1",
    "executable_target_chain": "v1",
    "order_state_machine": "v1",
    "runtime_critical_path": "v1",
    "performance_metric_contract": "v1",
    "participating_manifest": "v1",
    "failure_qualification": "v1",
    # Release 3（21–30）：Evidence of Necessity & Controlled Evolution
    "schema_release_hard_gate": "v1",
    "historical_integrity_corpus": "v1",
    "version_impact_release_gate": "v1",
    "oos_coverage_requirement": "v1",
    "constraint_keep_verdict": "v1",
    "risk_budget_lineage": "v1",
    "practicality_hard_gate": "v1",
    "oos_benchmark_table": "v1",
    "major_release_minimal_answer": "v1",
    "complexity_veto_release": "v1",
    # 数据健康检查报告优化：Daily Data Trust Report
    "daily_data_trust_report": "v1",
    # PWC-1 Production Wiring Closure（1–10）
    "path_hash_canonical_identity": "v1",
    "quality_gate_fail_closed": "v1",
    "data_trust_real_metrics": "v1",
    "certification_cross_binding": "v1",
    "release_context_in_snapshot_ledger": "v1",
    "ledger_commit_invariant_gate": "v1",
    "unknown_caps_no_new_risk": "v1",
    "formal_stress_canonical_only": "v1",
    "engine_participating_manifest": "v1",
    "pwc1_retirement_table": "v1",
    # PWC-2 Production Authority Graph & Physical Retirement
    "pwc2_authority_graph": "v1",
    # Minimal Trusted Production Release（12 项工作步骤）
    "minimal_trusted_release": "v1",
    # MTR Closure Release（Sprint A–E）
    "mtr_closure_behavioral_authority": "v1",
    "mtr_closure_pure_referee": "v1",
    "mtr_closure_feature_manifest_truth": "v1",
    # Runtime Evidence Closure（Sprint 1–4）
    "execution_context_mode": "v1",
    "deployment_cap": "v1",
    "broker_adapter_contract": "v1",
    "runtime_event_ledger": "v1",
    "research_outcome_ledger": "v1",
    "paper_order_pipeline": "v1",
    "runtime_evidence_artifact": "v1",
    # Runtime Evidence Wiring & Fail-Closed Closure（Sprint A–D）
    "runtime_evidence_wiring_fail_closed": "v1",
}


def feature_manifest_hash() -> str:
    raw = json.dumps(FEATURE_SET, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:16]


_IDENTITY = VersionIdentity()


def version_identity() -> VersionIdentity:
    """权威版本身份单例（生产只读此对象）。"""
    return _IDENTITY
