-- 1. 创建新表，将指定列的默认值改为 0（整数）
CREATE TABLE hk_daily_kline_analysis_new (
    id                                         INTEGER,
    stock_code                                 TEXT    NOT NULL,
    stock_name                                 TEXT    NOT NULL,
    date                                       TEXT    NOT NULL,
    open                                       REAL,
    high                                       REAL,
    low                                        REAL,
    close                                      REAL,
    volume                                     REAL,
    amount                                     REAL,
    amplitude                                  REAL,
    change_percent                             REAL,
    change_amount                              REAL,
    turnover_rate                              REAL,
    previous_close                             REAL,
    avg_price                                  REAL,
    close_chgpct                               REAL,
    avg_volume_5d                              REAL,
    volume_ratio5                              REAL,
    avg_volume_20d                             REAL,
    volume_ratio20                             REAL,
    ema5                                       REAL,
    ema8                                       REAL,
    ema10                                      REAL,
    ema12                                      REAL,
    ema13                                      REAL,
    ema20                                      REAL,
    ema21                                      REAL,
    ema26                                      REAL,
    ema30                                      REAL,
    ema34                                      REAL,
    ema50                                      REAL,
    ema60                                      REAL,
    ema63                                      REAL,
    ema100                                     REAL,
    ema120                                     REAL,
    ema200                                     REAL,
    ema250                                     REAL,
    bias5                                      REAL,
    bias10                                     REAL,
    bias20                                     REAL,
    bias50                                     REAL,
    bias60                                     REAL,
    bias100                                    REAL,
    bias120                                    REAL,
    bias200                                    REAL,
    bias250                                    REAL,
    vol_ema5                                   REAL,
    vol_ema10                                  REAL,
    vol_ema20                                  REAL,
    volume_oscillator                          REAL,
    obv                                        REAL,
    bollinger_middle                           REAL,
    bollinger_upper                            REAL,
    bollinger_lower                            REAL,
    vwap                                       REAL,
    parabolic_sar                              REAL,
    vol_ema5_20_cross_status                   REAL,
    vol_ema5_20_cross_streak                   REAL,
    vol_ema5_10_cross_status                   REAL,
    vol_ema5_10_cross_streak                   REAL,
    tr                                         REAL,
    atr14                                      REAL,
    kdj_k                                      REAL,
    kdj_d                                      REAL,
    kdj_j                                      REAL,
    macd_dif                                   REAL,
    macd_signal                                REAL,
    macd_histogram                             REAL,
    rsi6                                       REAL,
    rsi14                                      REAL,
    cci14                                      REAL,
    williams_r                                 REAL,
    pdi14                                      REAL,
    mdi14                                      REAL,
    adx14                                      REAL,
    atr30                                      REAL,
    pdi30                                      REAL,
    mdi30                                      REAL,
    adx30                                      REAL,
    atr60                                      REAL,
    pdi60                                      REAL,
    mdi60                                      REAL,
    adx60                                      REAL,
    atr100                                     REAL,
    pdi100                                     REAL,
    mdi100                                     REAL,
    adx100                                     REAL,
    mfi                                        REAL,
    ema_golden_cross                           INTEGER DEFAULT 0,
    ema_death_cross                            INTEGER DEFAULT 0,
    golden_triangle                            INTEGER DEFAULT 0,
    death_triangle                             INTEGER DEFAULT 0,
    macd_golden_cross                          INTEGER DEFAULT 0,
    macd_death_cross                           INTEGER DEFAULT 0,
    open_close_change_pct                      REAL,
    high_30d                                   REAL,
    low_30d                                    REAL,
    close_3d_ago                               REAL,
    high_125d                                  REAL,
    low_125d                                   REAL,
    high_250d                                  REAL,
    low_250d                                   REAL,
    volume_min_500d                            REAL,
    volume_max_500d                            REAL,
    volume_10th_percentile_500d                REAL,
    volume_25th_percentile_500d                REAL,
    volume_50th_percentile_500d                REAL,
    volume_75th_percentile_500d                REAL,
    volume_90th_percentile_500d                REAL,
    amount_min_500d                            REAL,
    amount_max_500d                            REAL,
    amount_10th_percentile_500d                REAL,
    amount_25th_percentile_500d                REAL,
    amount_50th_percentile_500d                REAL,
    amount_75th_percentile_500d                REAL,
    amount_90th_percentile_500d                REAL,
    amplitude_min_500d                         REAL,
    amplitude_max_500d                         REAL,
    amplitude_10th_percentile_500d             REAL,
    amplitude_25th_percentile_500d             REAL,
    amplitude_50th_percentile_500d             REAL,
    amplitude_75th_percentile_500d             REAL,
    amplitude_90th_percentile_500d             REAL,
    change_percent_min_500d                    REAL,
    change_percent_max_500d                    REAL,
    change_percent_10th_percentile_500d        REAL,
    change_percent_25th_percentile_500d        REAL,
    change_percent_50th_percentile_500d        REAL,
    change_percent_75th_percentile_500d        REAL,
    change_percent_90th_percentile_500d        REAL,
    change_amount_min_500d                     REAL,
    change_amount_max_500d                     REAL,
    change_amount_10th_percentile_500d         REAL,
    change_amount_25th_percentile_500d         REAL,
    change_amount_50th_percentile_500d         REAL,
    change_amount_75th_percentile_500d         REAL,
    change_amount_90th_percentile_500d         REAL,
    turnover_rate_min_500d                     REAL,
    turnover_rate_max_500d                     REAL,
    turnover_rate_10th_percentile_500d         REAL,
    turnover_rate_25th_percentile_500d         REAL,
    turnover_rate_50th_percentile_500d         REAL,
    turnover_rate_75th_percentile_500d         REAL,
    turnover_rate_90th_percentile_500d         REAL,
    volume_ratio5_min_500d                     REAL,
    volume_ratio5_max_500d                     REAL,
    volume_ratio5_10th_percentile_500d         REAL,
    volume_ratio5_25th_percentile_500d         REAL,
    volume_ratio5_50th_percentile_500d         REAL,
    volume_ratio5_75th_percentile_500d         REAL,
    volume_ratio5_90th_percentile_500d         REAL,
    volume_ratio20_min_500d                    REAL,
    volume_ratio20_max_500d                    REAL,
    volume_ratio20_10th_percentile_500d        REAL,
    volume_ratio20_25th_percentile_500d        REAL,
    volume_ratio20_50th_percentile_500d        REAL,
    volume_ratio20_75th_percentile_500d        REAL,
    volume_ratio20_90th_percentile_500d        REAL,
    price_amp_market_chip_concentration_20_70  REAL,
    price_amp_chip_price_range_20_70           REAL,
    price_amp_chip_min_20_70                   REAL,
    price_amp_chip_max_20_70                   REAL,
    price_amp_market_chip_concentration_20_90  REAL,
    price_amp_chip_price_range_20_90           REAL,
    price_amp_chip_min_20_90                   REAL,
    price_amp_chip_max_20_90                   REAL,
    price_amp_market_chip_concentration_60_70  REAL,
    price_amp_chip_price_range_60_70           REAL,
    price_amp_chip_min_60_70                   REAL,
    price_amp_chip_max_60_70                   REAL,
    price_amp_market_chip_concentration_60_90  REAL,
    price_amp_chip_price_range_60_90           REAL,
    price_amp_chip_min_60_90                   REAL,
    price_amp_chip_max_60_90                   REAL,
    price_amp_market_chip_concentration_250_70 REAL,
    price_amp_chip_price_range_250_70          REAL,
    price_amp_chip_min_250_70                  REAL,
    price_amp_chip_max_250_70                  REAL,
    price_amp_market_chip_concentration_250_90 REAL,
    price_amp_chip_price_range_250_90          REAL,
    price_amp_chip_min_250_90                  REAL,
    price_amp_chip_max_250_90                  REAL,
    price_amp_market_chip_concentration         REAL,
    price_amp_chip_price_range                  REAL,
    price_amp_chip_min                          REAL,
    price_amp_chip_max                          REAL,
    cost_spread_chip_min_20_70                 REAL,
    cost_spread_chip_max_20_70                 REAL,
    cost_spread_chip_price_range_20_70         REAL,
    cost_spread_chip_concentration_20_70       REAL,
    cost_spread_chip_min_20_90                 REAL,
    cost_spread_chip_max_20_90                 REAL,
    cost_spread_chip_price_range_20_90         REAL,
    cost_spread_chip_concentration_20_90       REAL,
    cost_spread_chip_min_60_70                 REAL,
    cost_spread_chip_max_60_70                 REAL,
    cost_spread_chip_price_range_60_70         REAL,
    cost_spread_chip_concentration_60_70       REAL,
    cost_spread_chip_min_60_90                 REAL,
    cost_spread_chip_max_60_90                 REAL,
    cost_spread_chip_price_range_60_90         REAL,
    cost_spread_chip_concentration_60_90       REAL,
    cost_spread_chip_min_250_70                REAL,
    cost_spread_chip_max_250_70                REAL,
    cost_spread_chip_price_range_250_70        REAL,
    cost_spread_chip_concentration_250_70      REAL,
    cost_spread_chip_min_250_90                REAL,
    cost_spread_chip_max_250_90                REAL,
    cost_spread_chip_price_range_250_90        REAL,
    cost_spread_chip_concentration_250_90      REAL,
    cost_spread_chip_concentration             REAL,
    intensive_trading_min                      REAL,
    intensive_trading_max                      REAL,
    ema5_10_status                             REAL,
    ema5_10_streak                             REAL,
    ema5_20_status                             REAL,
    ema5_20_streak                             REAL,
    ema10_20_status                            REAL,
    ema10_20_streak                            REAL,
    ema20_50_status                            REAL,
    ema20_50_streak                            REAL,
    ema50_200_status                           REAL,
    ema50_200_streak                           REAL,
    ema20_200_status                           REAL,
    ema20_200_streak                           REAL,
    ema12_26_status                            REAL,
    ema12_26_streak                            REAL,
    ema5_13_status                             REAL,
    ema5_13_streak                             REAL,
    ema5_34_status                             REAL,
    ema5_34_streak                             REAL,
    ema13_34_status                            REAL,
    ema13_34_streak                            REAL,
    ema5_13_34_status                          REAL,
    ema5_13_34_streak                          REAL,
    macd_status                                REAL,
    macd_golden_streak                         REAL,
    macd_death_streak                          REAL,
    bottom_signal_cond                         INTEGER DEFAULT 0,
    top_signal_cond                            INTEGER DEFAULT 0,
    bottom_entry_signal_cond                   INTEGER DEFAULT 0,
    top_exit_signal_cond                       INTEGER DEFAULT 0,
    continuation_signal_cond                   INTEGER DEFAULT 0,
    decline_continuation_cond                  INTEGER DEFAULT 0,
    accumulation_cond                          INTEGER DEFAULT 0,
    distribution_cond                          INTEGER DEFAULT 0,
    multi_timeframe_chip_confirm_bottom_cond   INTEGER DEFAULT 0,
    multi_timeframe_chip_confirm_top_cond      INTEGER DEFAULT 0,
    signal_quality                             TEXT,
    PRIMARY KEY (id)
);

-- 2. 复制所有数据
INSERT INTO hk_daily_kline_analysis_new SELECT * FROM hk_daily_kline_analysis;

-- 3. 删除旧表
DROP TABLE hk_daily_kline_analysis;

-- 4. 重命名新表
ALTER TABLE hk_daily_kline_analysis_new RENAME TO hk_daily_kline_analysis;

-- 5. 创建索引
CREATE INDEX idx_hk_daily_kline_analysis ON hk_daily_kline_analysis(stock_code, date);